# -*- coding: utf-8 -*-
"""exp4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FCTzpD56w4HcmERKcaQY4PKLIt85vyT
"""

import nltk
from nltk.util import ngrams
from collections import Counter
import matplotlib.pyplot as plt
import string

# Download the 'punkt_tab' resource using nltk.download
nltk.download('punkt_tab')

# Rest of your code remains the same...
translator = str.maketrans('', '', string.punctuation)
text_clean = text.lower().translate(translator)
tokens = nltk.word_tokenize(text_clean)

# ... (rest of the code)

text = """The quick brown fox jumps over the lazy dog. The dog is lazy but the fox is quick."""

n = 2  # Example for bigrams

n_grams = list(ngrams(tokens, n))

n_gram_freq = Counter(n_grams)

print(f"Top {n}-grams:")

print(n_gram_freq.most_common(5))

top_n_grams = n_gram_freq.most_common(10)

labels = [' '.join(gram) for gram, count in top_n_grams]

values = [count for gram, count in top_n_grams]

plt.barh(labels, values)

plt.title(f"Top {n}-grams Frequency")

plt.show()

n = 1 # Example for uigrams

n_grams = list(ngrams(tokens, n))

n_gram_freq = Counter(n_grams)

print(f"Top {n}-grams:")

print(n_gram_freq.most_common(5))

top_n_grams = n_gram_freq.most_common(10)

labels = [' '.join(gram) for gram, count in top_n_grams]

values = [count for gram, count in top_n_grams]

plt.barh(labels, values)

plt.title(f"Top {n}-grams Frequency")

plt.show()

n = 3  # Example for trigrams

n_grams = list(ngrams(tokens, n))

n_gram_freq = Counter(n_grams)

print(f"Top {n}-grams:")

print(n_gram_freq.most_common(5))

top_n_grams = n_gram_freq.most_common(10)

labels = [' '.join(gram) for gram, count in top_n_grams]

values = [count for gram, count in top_n_grams]

plt.barh(labels, values)

plt.title(f"Top {n}-grams Frequency")

plt.show()